### PR TITLE
fix(#12): addtional fixes for publishers

### LINKED ISSUE #101: More checks on publishers code hosting URLs
See https://github.com/italia/developers-italia-onboarding/issues/195

### PR DESCRIPTION
**Pull request by LorenzoS92**
Addiotional Fixes for comments in #12 for Publishers

* Fix docs
* Fix payload for POST publisher

Still remaining:
* Update tests

### CODE REVIEW

File: main_test.go [hunk 1]
```diff
@@ -184,7 +184,7 @@ func TestPublishersEndpoints(t *testing.T) {
 		},
 		{
 			query: "POST /v1/publishers",
-			body:  `{"URL":"https://www.example.com", "email":"example@example.com"}`,
+			body:  `{"codeHosting": [{"url" : "https://www.example.com"}], "email":"example@example.com"}`,
```
Comment (bfabio) [inline main_test.go:187]: Pagination will come in another PR, right?

**Review by bfabio — APPROVED** [review]

File: main_test.go (hunk 1 above)
Comment (LorenzoS92) [reply main_test.go:187]: yep!
